version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: werewolf-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - werewolf-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: werewolf-backend
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${SERVER_PORT}:8080"
    networks:
      - werewolf-network

volumes:
  postgres_data:

networks:
  werewolf-network:
    driver: bridge